### ISSUE TITLE
Redefining Kernel breaks interpreter

### ISSUE THREAD

**Issue by Nicd** [mrshankly/tryelixir#10]
I wrote something like

```elixir
defmodule Kernel do
  def foo(), do: 1
end
```

into the REPL at https://tryelixir.net/ and now it just returns "error" for everything (500 Internal Server Error). I don't know if it died due to that but the timing seems suspect. Sorry about that. :(

**Comment by mrshankly** [comment]
Lol that's a nice one! Don't worry about breaking it, I just ask you to report it if you find something. So thank you for doing that!

It should be up again now, I'll have a fix for this soon.

Thank you.
